version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=newsdb
      - POSTGRES_USER=newsuser
      - POSTGRES_PASSWORD=developer
    ports:
      - "5432:5432"

  web:
    restart: always
    build: .
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py test && python manage.py create_news
      && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
